# MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  # import application-oauth.yml
  profiles:
    include: oauth

  # JPA
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    # open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            client-name:
            authorization-grant-type:
            redirect-uri:
            client-authentication-method:
            scopt:
              -
              -

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# jwt secret key
jwt:
  secret: 4f7bef3a1c993e191bc51fd532c309aa3d0c0686657fc832113fc8ff726ce63bc0f190e2fcb7db3a8cd373e3e63c81449f44f08ebe5fed3a0d365443a6ee38eb

# auth : for normal user | oauth2 : for kakao user
app:
  auth:
    token-secret:
    token-expiry:
    refresh-token-expiry:
  oauth2:
    authorized-redirect-uris:

# log level setting
logging:
  level:
    root: info
    com:
      bbb: debug

# openVidu Environmental Variables
OPENVIDU_URL: https://i8b106.p.ssafy.io:8443
OPENVIDU_SECRET:

# context path
server:
  servlet:
    context-path: /api


